name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu Kopyala
      uses: actions/checkout@v4

    - name: Buildozer ile APK Derle (Docker)
      uses: docker://kivy/buildozer:latest
      env:
        BUILDER_ALLOW_ROOT: "true"
      with:
        args: android debug

    - name: APK Dosyasını Kaydet (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: zenith-apk
        path: bin/*.apk
